package cn.itcast.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://dao.cxf.itcast.cn/")
public interface ProductService {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "saveProduct", targetNamespace = "http://dao.cxf.itcast.cn/", className = "cn.itcast.cxf.SaveProduct")
	@ResponseWrapper(localName = "saveProductResponse", targetNamespace = "http://dao.cxf.itcast.cn/", className = "cn.itcast.cxf.SaveProductResponse")
	public void saveProduct(@WebParam(name = "arg0", targetNamespace = "") Product arg0);

	/**
	 * 
	 * @param arg0
	 * @return
	 *     returns cn.itcast.cxf.Product
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getProduct", targetNamespace = "http://dao.cxf.itcast.cn/", className = "cn.itcast.cxf.GetProduct")
	@ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://dao.cxf.itcast.cn/", className = "cn.itcast.cxf.GetProductResponse")
	public Product getProduct(@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
