package cn.itcast.cxf.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserServiceI", targetNamespace = "http://service.project.market.com/")
public interface UserServiceI {

	/**
	 * 
	 * @param arg0
	 * @return
	 *     returns cn.itcast.cxf.user.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "loadByUsername", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.LoadByUsername")
	@ResponseWrapper(localName = "loadByUsernameResponse", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.LoadByUsernameResponse")
	public User loadByUsername(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updatePWD", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.UpdatePWD")
	@ResponseWrapper(localName = "updatePWDResponse", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.UpdatePWDResponse")
	public void updatePWD(@WebParam(name = "arg0", targetNamespace = "") Integer arg0, @WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return
	 *     returns cn.itcast.cxf.user.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "save", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.SaveResponse")
	public User save(@WebParam(name = "arg0", targetNamespace = "") User arg0);

	/**
	 * 
	 * @param arg0
	 * @return
	 *     returns cn.itcast.cxf.user.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateUser", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.UpdateUser")
	@ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.UpdateUserResponse")
	public User updateUser(@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return
	 *     returns cn.itcast.cxf.user.Pager
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "list", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.List")
	@ResponseWrapper(localName = "listResponse", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.ListResponse")
	public Pager list(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.DeleteResponse")
	public void delete(@WebParam(name = "arg0", targetNamespace = "") User arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "update", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.Update")
	@ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.UpdateResponse")
	public void update(@WebParam(name = "arg0", targetNamespace = "") User arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return
	 *     returns cn.itcast.cxf.user.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "login", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.Login")
	@ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.project.market.com/", className = "cn.itcast.cxf.user.LoginResponse")
	public User login(@WebParam(name = "arg0", targetNamespace = "") String arg0, @WebParam(name = "arg1", targetNamespace = "") String arg1);

}
