package cn.itcast.cxf.user;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
* <p>
* An example of how this class may be used:
* <pre>
* UserServiceIService service = new UserServiceIService();
* UserServiceI portType = service.getUserServiceIPort();
* portType.loadByUsername(...);
* </pre>
* </p>
 * 
 */
@WebServiceClient(name = "UserServiceIService", targetNamespace = "http://service.project.market.com/", wsdlLocation = "http://localhost:8080/Gary_ssh_maven/services/userCXFService?wsdl")
public class UserServiceIService extends Service {

	private final static URL USERSERVICEISERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(cn.itcast.cxf.user.UserServiceIService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.itcast.cxf.user.UserServiceIService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/Gary_ssh_maven/services/userCXFService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/Gary_ssh_maven/services/userCXFService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERSERVICEISERVICE_WSDL_LOCATION = url;
	}

	public UserServiceIService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserServiceIService() {
		super(USERSERVICEISERVICE_WSDL_LOCATION, new QName("http://service.project.market.com/", "UserServiceIService"));
	}

	/**
	 * 
	 * @return
	 *     returns UserServiceI
	 */
	@WebEndpoint(name = "UserServiceIPort")
	public UserServiceI getUserServiceIPort() {
		return super.getPort(new QName("http://service.project.market.com/", "UserServiceIPort"), UserServiceI.class);
	}

}
