package cn.jbit.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IProductService", targetNamespace = "http://service.cxf.jbit.cn/")
public interface IProductService {

	/**
	 * 
	 * @param arg0
	 * @return
	 *     returns cn.jbit.cxf.Product
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPorductById", targetNamespace = "http://service.cxf.jbit.cn/", className = "cn.jbit.cxf.GetPorductById")
	@ResponseWrapper(localName = "getPorductByIdResponse", targetNamespace = "http://service.cxf.jbit.cn/", className = "cn.jbit.cxf.GetPorductByIdResponse")
	public Product getPorductById(@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "addProduct", targetNamespace = "http://service.cxf.jbit.cn/", className = "cn.jbit.cxf.AddProduct")
	@ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://service.cxf.jbit.cn/", className = "cn.jbit.cxf.AddProductResponse")
	public void addProduct(@WebParam(name = "arg0", targetNamespace = "") Product arg0);

}
