package cn.jbit.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
* <p>
* An example of how this class may be used:
* <pre>
* IProductServiceService service = new IProductServiceService();
* IProductService portType = service.getIProductServicePort();
* portType.getPorductById(...);
* </pre>
* </p>
 * 
 */
@WebServiceClient(name = "IProductServiceService", targetNamespace = "http://service.cxf.jbit.cn/", wsdlLocation = "http://localhost:8080/CXFSpringServer/services/productServiceI2?wsdl")
public class IProductServiceService extends Service {

	private final static URL IPRODUCTSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(cn.jbit.cxf.IProductServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.jbit.cxf.IProductServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/CXFSpringServer/services/productServiceI2?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/CXFSpringServer/services/productServiceI2?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		IPRODUCTSERVICESERVICE_WSDL_LOCATION = url;
	}

	public IProductServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IProductServiceService() {
		super(IPRODUCTSERVICESERVICE_WSDL_LOCATION, new QName("http://service.cxf.jbit.cn/", "IProductServiceService"));
	}

	/**
	 * 
	 * @return
	 *     returns IProductService
	 */
	@WebEndpoint(name = "IProductServicePort")
	public IProductService getIProductServicePort() {
		return super.getPort(new QName("http://service.cxf.jbit.cn/", "IProductServicePort"), IProductService.class);
	}

}
